sdjournal: simplify/fix tests
Let's put common testing code into functions, and also use
t.Cleanup, t.Helper, and t.Fatalf instead of returning an error.

This makes the code smaller, and (indirectly) fixes a bunch of linter
warnings like these:

	sdjournal/journal_test.go:225:60: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
			return nil, nil, fmt.Errorf("Error opening journal: %s", err)
										 ^

	sdjournal/journal_test.go:157:15: Error return value of `j.Close` is not checked (errcheck)
		defer j.Close()
			     ^

	sdjournal/journal_test.go:165:3: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
			t.Fatalf(err.Error())
			^

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>