activation: Files: fix ercheck warnings
This one:
	activation/files_unix.go:42:20: Error return value of `os.Unsetenv` is not checked (errcheck)

Since
 - current unix implementation of os.Unsetenv never returns an error;
 - there is no way to return an error;
let's just ignore it.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>